# -*- coding: utf-8 -*-
"""heat_map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C8tLwVvtWky8XuoMdQlwCQ09LcvUBt6O
"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

img=tf.keras.preprocessing.image.load_img("/content/ele.jpg",target_size=(224, 224))

plt.imshow(img)

x=tf.keras.preprocessing.image.img_to_array(img)
shape=x.shape
x=np.expand_dims(x,axis=0)
x=tf.keras.applications.resnet50.preprocess_input(x)

resnet=tf.keras.applications.resnet50.ResNet50(input_shape=shape)

resnet.summary()

weights=resnet.layers[-1].get_weights()

pic_model=tf.keras.Model(resnet.input,resnet.layers[-3].output)

class_targ=np.argmax(resnet.predict(x)[0])

feature_pic=pic_model.predict(x)[0]

w=weights[0][:,class_targ]

t=feature_pic.dot(w)

import scipy

t=scipy.ndimage.zoom(t,(32,32),order=1)

plt.imshow(img,alpha=0.8)
plt.imshow(t,cmap="jet",alpha=0.5)

